# Built application files
*.apk
*.ap_

# Files for the Dalvik VM
*.dex

# Java class files
*.class

# Generated files
bin/
gen/

# Gradle files
.gradle/
build/

# Local configuration file (sdk path, etc)
local.properties

# Proguard folder generated by Eclipse
proguard/

# IntelliJ files
.idea
*.iml

# Maven output folder
target

# Misc
.DS_Store
Thumbs.db
*.swp
*.bak